// Canonical 70-component name list. Stable export so the layout
// sidebar, catalog page, and getStaticPaths all read from one source.
// Order = sidebar render order (alphabetical for browsing, but we
// override a few to group sensibly).

const NAMES = [
  "Button",
  "Input",
  "Textarea",
  "Select",
  "Checkbox",
  "Radio",
  "RadioGroup",
  "Switch",
  "Toggle",
  "Slider",
  "NumberInput",
  "SearchInput",
  "FileUploader",
  "DatePicker",
  "DateRangePicker",
  "TimePicker",
  "Combobox",
  "MultiCombobox",
  "PinInput",
  "ColorPicker",
  "PhoneInputKR",
  "AddressInputKR",
  "FormField",
  "SegmentedControl",

  "Tag",
  "Chip",
  "Badge",
  "Avatar",
  "Card",
  "Stat",
  "Skeleton",
  "Spinner",
  "ProgressBar",
  "Stepper",
  "Divider",
  "EmptyState",
  "Quote",
  "Banner",
  "Alert",
  "Timeline",
  "Hint",
  "Kbd",
  "KeyboardShortcut",
  "Code",
  "CodeBlock",
  "DescriptionList",
  "Image",

  "Tabs",
  "Accordion",
  "Disclosure",
  "Breadcrumb",
  "Pagination",
  "Toolbar",
  "Menu",
  "TreeView",

  "Modal",
  "Drawer",
  "Sheet",
  "Tooltip",
  "Popover",
  "HoverCard",
  "ContextMenu",
  "Command",
  "Toast",

  "Calendar",
  "Carousel",
  "DataTable",
  "ChartLine",
  "ChartBar",
  "Resizable",
];

export default NAMES;

/** Catalog entry — tagline shown on the catalog landing page and
 *  per-component detail page. Same Korean copy as docs_site.rs. */
export const CATALOG: Record<string, { tagline: string }> = {
  Button: { tagline: "기본 인터랙션 — 4 variant × 3 size × loading 상태" },
  Input: { tagline: "텍스트 입력 — error + aria-invalid 자동 연결" },
  Textarea: { tagline: "여러 줄 입력 — resize 세로만" },
  Select: { tagline: "단일 선택 드롭다운" },
  Checkbox: { tagline: "다중 선택 + label 자동 wrap" },
  Radio: { tagline: "단일 선택" },
  RadioGroup: { tagline: "Radio 묶음 — name + value/onChange" },
  Switch: { tagline: "ON/OFF 토글 — role=switch + aria-checked" },
  Toggle: { tagline: "아이콘 토글 — Switch와 다름. 편집기 툴바용" },
  Slider: { tagline: "범위 입력 — accent-color 자동" },
  NumberInput: { tagline: "수량/금액 입력 — +/- 버튼" },
  SearchInput: { tagline: "검색 — clear 버튼 포함" },
  FileUploader: { tagline: "드래그앤드롭 — 키보드 fallback" },
  DatePicker: { tagline: "HTML5 date input — locale 자동" },
  DateRangePicker: { tagline: "기간 선택 — start ≤ end 강제" },
  TimePicker: { tagline: "HH:mm — 분 단위 step prop" },
  Combobox: { tagline: "자동완성 — 한글 검색 키 지원" },
  MultiCombobox: { tagline: "다중 선택 자동완성 — chip 입력" },
  PinInput: { tagline: "OTP / 본인 인증 6자리" },
  ColorPicker: { tagline: "swatch + hex 동기화" },
  PhoneInputKR: { tagline: "010-XXXX-XXXX 자동 mask" },
  AddressInputKR: { tagline: "우편번호 + 도로명 + 상세 + Daum 검색 hook" },
  FormField: { tagline: "label + hint + error 자동 ARIA 연결" },
  SegmentedControl: { tagline: "필터 탭 — 토스 스타일 pill" },

  Tag: { tagline: "라벨 — neutral / success / warning / danger" },
  Chip: { tagline: "제거 가능한 태그" },
  Badge: { tagline: "카운트 + dot — 알림 뱃지" },
  Avatar: { tagline: "프로필 — initials 또는 src" },
  Card: { tagline: "콘텐츠 컨테이너" },
  Stat: { tagline: "KPI — 라벨 + 값 + 증감" },
  Skeleton: { tagline: "로딩 placeholder — shimmer" },
  Spinner: { tagline: "로딩 인디케이터 — role=status" },
  ProgressBar: { tagline: "진행률 — role=progressbar" },
  Stepper: { tagline: "다단계 진행 — 본인 인증 → 계좌 등록 → 완료" },
  Divider: { tagline: "수평/수직 구분선" },
  EmptyState: { tagline: "결과 없음 / 빈 상태" },
  Quote: { tagline: "에디토리얼 인용 + cite" },
  Timeline: { tagline: "주문/배송/진행 단계 표시" },
  Banner: { tagline: "지속 표시 배너 — Toast과 다름" },
  Alert: { tagline: "인라인 알림 — Banner와 다름" },
  Hint: { tagline: "간단 안내 텍스트" },
  Kbd: { tagline: "키보드 단축키 표시" },
  KeyboardShortcut: { tagline: "Kbd 묶음 — 검색 ⌘+K" },
  Code: { tagline: "인라인 코드" },
  CodeBlock: { tagline: "코드 블록 + 복사 버튼" },
  DescriptionList: { tagline: "제품 사양 dt/dd" },
  Image: { tagline: "fallback + lazy loading" },

  Tabs: { tagline: "탭 + 패널 — 전체 ARIA tablist" },
  Accordion: { tagline: "FAQ / 접힘" },
  Disclosure: { tagline: "단일 펼치기/접기" },
  Breadcrumb: { tagline: "경로 표시" },
  Pagination: { tagline: "페이지 네비게이션" },
  Toolbar: { tagline: "role=toolbar + Separator" },
  Menu: { tagline: "role=menu + MenuItem" },
  TreeView: { tagline: "중첩 트리 — 카테고리 / 파일" },

  Modal: { tagline: "중앙 다이얼로그 — Escape + aria-modal" },
  Drawer: { tagline: "우측 패널 — 데스크톱" },
  Sheet: { tagline: "바텀시트 — 모바일 우선" },
  Tooltip: { tagline: "호버 도움말" },
  Popover: { tagline: "클릭 → 열림" },
  HoverCard: { tagline: "호버 → 카드. 프로필 미리보기" },
  ContextMenu: { tagline: "우클릭 메뉴" },
  Command: { tagline: "⌘K 명령 팔레트 — 키보드 nav + 필터" },
  Toast: { tagline: "임시 알림 — useToast 훅" },

  Calendar: { tagline: "월별 그리드 — 한글 요일" },
  Carousel: { tagline: "슬라이더 — 화살표 + 도트" },
  DataTable: { tagline: "정렬 가능한 표" },
  ChartLine: { tagline: "inline SVG 라인 차트" },
  ChartBar: { tagline: "inline SVG 막대 차트" },
  Resizable: { tagline: "두 패널 분할 — 드래그 핸들" },
};
