/**
 * Gate 1 SSR smoke spec — three assertion layers per component.
 *
 * Build layer is implicit: if `next build` exited non-zero this spec
 * never runs (the harness shell script fails first). Inside this spec
 * we verify hydration + themed-render.
 *
 * Pulls the same component-names list from a JSON file that Next.js
 * also reads — single source of truth, regenerated by the harness
 * `prepare-fixture.sh` script if components change.
 */

import { test, expect, Page } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";

// Read the catalog by introspecting the component-registry source.
// We grep for top-level keys like `Button: {` so we don't have to
// duplicate the list. This stays in sync with components-registry.tsx
// automatically.
function readComponentNames(): string[] {
  const registryPath = path.resolve(__dirname, "../next-app/app/components-registry.tsx");
  const src = fs.readFileSync(registryPath, "utf-8");
  const names = new Set<string>();
  for (const match of src.matchAll(/^\s{2}([A-Z][A-Za-z0-9]+):\s*\{/gm)) {
    names.add(match[1]);
  }
  return [...names].sort();
}

const COMPONENT_NAMES = readComponentNames();

test.describe("Gate 1 SSR smoke matrix", () => {
  test(`fixture has at least 50 components (got ${COMPONENT_NAMES.length})`, () => {
    expect(COMPONENT_NAMES.length).toBeGreaterThanOrEqual(50);
  });

  for (const name of COMPONENT_NAMES) {
    test(`${name} — build / hydrate / themed-render`, async ({ page }) => {
      const errors: string[] = [];
      const warnings: string[] = [];

      page.on("console", (msg) => {
        const text = msg.text();
        if (msg.type() === "error") errors.push(text);
        if (msg.type() === "warning") warnings.push(text);
      });
      page.on("pageerror", (err) => {
        errors.push(`pageerror: ${err.message}`);
      });

      const response = await page.goto(`/c/${name}`, { waitUntil: "networkidle" });

      // --- Layer 1: build / route ---
      expect(response, `route /c/${name} responded`).not.toBeNull();
      expect(response!.status(), `HTTP status for /c/${name}`).toBe(200);

      // --- Layer 2: hydration ---
      // React surfaces hydration mismatches in console; assert none.
      const hydrationLike = (text: string) =>
        /hydrat(ion|ed|ing)|server-rendered HTML|did not match|Hydration failed|Text content did not match|Expected server HTML/i.test(text);
      const hydrationErrors = errors.filter(hydrationLike);
      const hydrationWarnings = warnings.filter(hydrationLike);

      expect(
        { errors: hydrationErrors, warnings: hydrationWarnings },
        `hydration must be clean for ${name}`,
      ).toEqual({ errors: [], warnings: [] });

      // --- Layer 3: themed render ---
      // Find any element inside the component root that has an aph-*
      // class and check it resolved a non-default background or text
      // color (i.e. our CSS variables reached the DOM).
      const root = page.locator('[data-testid="component-root"]');
      // Use `attached` not `visible`: overlay primitives (Modal/Drawer/
      // Sheet) render via position:fixed children so the wrapper itself
      // collapses to 0×0. Checking attached confirms SSR produced the
      // markup; the themed-render assertion below catches actual paint.
      await expect(root, `${name} root attached`).toBeAttached();

      const themed = await root.evaluate((el) => {
        // Walk root + descendants AND the entire main element. Some
        // primitives (Modal/Drawer/Sheet) use position:fixed and render
        // outside the component-root flow — they still belong to the
        // page and are valid themed signals.
        const main = (el as HTMLElement).closest("main") ?? document.body;
        const candidates: HTMLElement[] = Array.from(main.querySelectorAll("*")) as HTMLElement[];
        // rgb(0,0,0) IS a valid theme choice (black text/border is legit).
        // Only reject genuinely-unset values: transparent + zero-alpha + empty.
        const isDefault = (v: string) =>
          !v || v === "rgba(0, 0, 0, 0)" || v === "transparent" || v === "auto" || v === "none";
        for (const node of candidates) {
          const cs = window.getComputedStyle(node);
          const candidates2: Array<[string, string | undefined]> = [
            ["bg", cs.backgroundColor],
            ["color", cs.color],
            ["btc", cs.borderTopColor],
            ["bbc", cs.borderBottomColor],
            ["blc", cs.borderLeftColor],
            ["brc", cs.borderRightColor],
            // Skeleton uses background: linear-gradient(...) — that's
            // a non-"none" background-image. Theme signal too.
            ["bgi", cs.backgroundImage === "none" ? undefined : cs.backgroundImage],
            // Native form controls (Checkbox, Radio, Slider) theme via accent-color.
            ["accent", (cs as unknown as { accentColor?: string }).accentColor],
            // SVG charts theme via fill/stroke
            ["fill", (cs as unknown as { fill?: string }).fill],
            ["stroke", (cs as unknown as { stroke?: string }).stroke],
          ];
          for (const [label, v] of candidates2) {
            if (!isDefault(v ?? "")) {
              return { themed: true, sample: { tag: node.tagName, cls: node.className, [label]: v } };
            }
          }
        }
        return { themed: false, sample: null };
      });
      expect(themed.themed, `${name} should resolve at least one themed CSS var (got ${JSON.stringify(themed.sample)})`).toBe(true);

      // Surface any non-hydration errors so they don't silently pile
      // up — they're often genuine bugs even if not blocking.
      const nonHydrationErrors = errors.filter((e) => !hydrationLike(e));
      if (nonHydrationErrors.length > 0) {
        console.log(`[${name}] non-hydration errors:`, nonHydrationErrors);
      }
    });
  }
});
